name: CD
on:
  push:
    tags:
      - '*'

jobs:
  deploy-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build the latest Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/worker:latest --tag ${{ secrets.DOCKERHUB_USERNAME }}/worker:${{ env.RELEASE_VERSION }}
      - name: Push the latest Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/worker  --all-tags