name: Installers creation

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd gui
          npm install --frozen-lockfile

      - name: Build project
        run: |
          cd gui
          npm run build

      - name: Create Linux distribution
        run: |
          cd gui
          npm run dist

      - name: List Linux release directory contents
        run: |
          cd gui/release
          ls -l

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd gui
          npm install --frozen-lockfile

      - name: Build project
        run: |
          cd gui
          npm run build

      - name: Create Windows distribution
        run: |
          cd gui
          npm run dist

      - name: List Windows release directory contents
        run: |
          cd gui/release
          dir

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd gui
          npm install --frozen-lockfile

      - name: Build project
        run: |
          cd gui
          npm run build

      - name: Create macOS distribution
        run: |
          cd gui
          npm run dist

      - name: List macOS release directory contents
        run: |
          cd gui/release
          ls -l
